---
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine-jdk17
    container_name: jenkins
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - "jenkins-data:/var/jenkins_home"
    networks:
      - jenkins
    restart: on-failure

volumes:
  jenkins-data:

networks:
  jenkins:
