---
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "80:8081"
    volumes:
      - "nexus-data:/nexus-data"
    networks:
      - nexus
    stop_grace_period: 2m
    restart: on-failure

volumes:
  nexus-data:

networks:
  nexus:
